export const DELETE_ENTRY = 'DELETE_ENTRY';
export const ADD_ENTRY = 'ADD_ENTRY';
export const REQUEST_ENTRIES = 'REQUEST_ENTRIES';
export const RECEIVE_ENTRIES = 'RECEIVE_ENTRIES';
export const INVALIDATE_ENTRIES = 'INVALIDATE_ENTRIES';


