export const REQUEST_DELETE_ENTRIES = 'REQUEST_DELETE_ENTRIES';
export const RECEIVE_DELETED_ENTRY_IDS = 'RECEIVE_DELETED_ENTRY_IDS';
export const RECEIVE_NEW_ENTRY = 'RECEIVE_NEW_ENTRY';
export const REQUEST_ADD_ENTRY = 'REQUEST_ADD_ENTRY';
export const REQUEST_ENTRIES = 'REQUEST_ENTRIES';
export const RECEIVE_ENTRIES = 'RECEIVE_ENTRIES';
export const INVALIDATE_ENTRIES = 'INVALIDATE_ENTRIES';


